# Generated by Django 4.0.1 on 2022-01-16 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_store',
            fields=[
                ('book_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('book_auth', models.CharField(max_length=50)),
                ('book_page', models.IntegerField()),
                ('book_image', models.ImageField(upload_to='pic')),
                ('book_pdf', models.FileField(upload_to='pdfs/')),
                ('book_publisher', models.CharField(max_length=50)),
                ('book_publish', models.DateField(default='2000-01-01')),
            ],
        ),
    ]
