# Generated by Django 4.0.1 on 2022-01-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_store',
            name='book_publisher',
            field=models.CharField(default=1998, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book_store',
            name='book_publish',
            field=models.DateField(),
        ),
    ]
