# Generated by Django 4.0.1 on 2022-02-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_store',
            fields=[
                ('book_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('book_auth', models.CharField(max_length=100)),
                ('book_page', models.IntegerField()),
                ('book_publish', models.DateField(default='2000-01-01')),
                ('book_publisher', models.CharField(max_length=100)),
                ('book_image', models.ImageField(upload_to='book_image_file')),
                ('book_pdf', models.FileField(upload_to='book_pdf_file')),
            ],
        ),
    ]
